export default {
    rotateLeft: false,
    rotateRight: false,
    moveForward: false,
    moveBackwards: false,
    Level: 1,
    Difficulty: 2,
    CurNum: 0,
    mapconfig: [
        [
            { id: 0, type: "wall" },
            { id: 1, type: "wall" },
            { id: 2, type: "wall" },
            { id: 3, type: "wall" },
            { id: 4, type: "wall" },
            { id: 5, type: "wall" },
            { id: 6, type: "wall" },
            { id: 7, type: "wall" },
            { id: 8, type: "wall" },
            { id: 9, type: "wall" },
        ],
        [
            { id: 10, type: "wall" },
            { id: 11, type: "light" },
            { id: 12, type: "open" },
            { id: 13, type: "light" },
            { id: 14, type: "open" },
            { id: 15, type: "open" },
            { id: 16, type: "light" },
            { id: 17, type: "open" },
            { id: 18, type: "light" },
            { id: 19, type: "wall" },
        ],
        [
            { id: 20, type: "wall" },
            { id: 21, type: "open" },
            { id: 22, type: "wall" },
            { id: 23, type: "wall" },
            { id: 24, type: "open" },
            { id: 25, type: "light" },
            { id: 26, type: "wall" },
            { id: 27, type: "wall" },
            { id: 28, type: "open" },
            { id: 29, type: "wall" },
        ],
        [
            { id: 30, type: "wall" },
            { id: 31, type: "light" },
            { id: 32, type: "wall" },
            { id: 33, type: "wall" },
            { id: 34, type: "light" },
            { id: 35, type: "open" },
            { id: 36, type: "wall" },
            { id: 37, type: "wall" },
            { id: 38, type: "light" },
            { id: 39, type: "wall" },
        ],
        [
            { id: 40, type: "wall" },
            { id: 41, type: "open" },
            { id: 42, type: "wall" },
            { id: 43, type: "wall" },
            { id: 44, type: "open" },
            { id: 45, type: "light" },
            { id: 46, type: "wall" },
            { id: 47, type: "wall" },
            { id: 48, type: "open" },
            { id: 49, type: "wall" },
        ],
        [
            { id: 50, type: "wall" },
            { id: 51, type: "open" },
            { id: 52, type: "wall" },
            { id: 53, type: "wall" },
            { id: 54, type: "open" },
            { id: 55, type: "open" },
            { id: 56, type: "wall" },
            { id: 57, type: "wall" },
            { id: 58, type: "open" },
            { id: 59, type: "wall" },
        ],
        [
            { id: 60, type: "wall" },
            { id: 61, type: "light" },
            { id: 62, type: "wall" },
            { id: 63, type: "wall" },
            { id: 64, type: "wall" },
            { id: 65, type: "wall" },
            { id: 66, type: "wall" },
            { id: 67, type: "wall" },
            { id: 68, type: "light" },
            { id: 69, type: "wall" },
        ],
        [
            { id: 70, type: "wall" },
            { id: 71, type: "open" },
            { id: 72, type: "wall" },
            { id: 73, type: "wall" },
            { id: 74, type: "wall" },
            { id: 75, type: "wall" },
            { id: 76, type: "wall" },
            { id: 77, type: "wall" },
            { id: 78, type: "open" },
            { id: 79, type: "wall" },
        ],
        [
            { id: 80, type: "wall" },
            { id: 81, type: "light" },
            { id: 82, type: "open" },
            { id: 83, type: "light" },
            { id: 84, type: "open" },
            { id: 85, type: "open" },
            { id: 86, type: "light" },
            { id: 87, type: "open" },
            { id: 88, type: "light" },
            { id: 89, type: "wall" },
        ],
        [
            { id: 90, type: "wall" },
            { id: 91, type: "wall" },
            { id: 92, type: "wall" },
            { id: 93, type: "wall" },
            { id: 94, type: "wall" },
            { id: 95, type: "wall" },
            { id: 96, type: "wall" },
            { id: 97, type: "wall" },
            { id: 98, type: "wall" },
            { id: 99, type: "wall" },
        ]
    ],
    currentSudoku: [],
    BaseSudoku: [],
    WhiteLeft: 0,
    Inair: false,

}